//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.18 at 11:17:48 AM ICT 
//


package com.ant.crawler.core.conf.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entityFields">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rssSite" type="{}rssSite"/>
 *                   &lt;element name="listSite" type="{}listSite"/>
 *                   &lt;element name="detailSite" type="{}detailSite"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="categories" type="{}categories"/>
 *       &lt;/sequence>
 *       &lt;attribute name="backend" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityFields",
    "categories"
})
@XmlRootElement(name = "entityConf")
public class EntityConf {

    @XmlElement(required = true)
    protected EntityConf.EntityFields entityFields;
    @XmlElement(required = true)
    protected Categories categories;
    @XmlAttribute(name = "backend")
    protected String backend;

    /**
     * Gets the value of the entityFields property.
     * 
     * @return
     *     possible object is
     *     {@link EntityConf.EntityFields }
     *     
     */
    public EntityConf.EntityFields getEntityFields() {
        return entityFields;
    }

    /**
     * Sets the value of the entityFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityConf.EntityFields }
     *     
     */
    public void setEntityFields(EntityConf.EntityFields value) {
        this.entityFields = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link Categories }
     *     
     */
    public Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Categories }
     *     
     */
    public void setCategories(Categories value) {
        this.categories = value;
    }

    /**
     * Gets the value of the backend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackend() {
        return backend;
    }

    /**
     * Sets the value of the backend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackend(String value) {
        this.backend = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rssSite" type="{}rssSite"/>
     *         &lt;element name="listSite" type="{}listSite"/>
     *         &lt;element name="detailSite" type="{}detailSite"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rssSite",
        "listSite",
        "detailSite"
    })
    public static class EntityFields {

        @XmlElement(required = true)
        protected RssSite rssSite;
        @XmlElement(required = true)
        protected ListSite listSite;
        @XmlElement(required = true)
        protected DetailSite detailSite;

        /**
         * Gets the value of the rssSite property.
         * 
         * @return
         *     possible object is
         *     {@link RssSite }
         *     
         */
        public RssSite getRssSite() {
            return rssSite;
        }

        /**
         * Sets the value of the rssSite property.
         * 
         * @param value
         *     allowed object is
         *     {@link RssSite }
         *     
         */
        public void setRssSite(RssSite value) {
            this.rssSite = value;
        }

        /**
         * Gets the value of the listSite property.
         * 
         * @return
         *     possible object is
         *     {@link ListSite }
         *     
         */
        public ListSite getListSite() {
            return listSite;
        }

        /**
         * Sets the value of the listSite property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListSite }
         *     
         */
        public void setListSite(ListSite value) {
            this.listSite = value;
        }

        /**
         * Gets the value of the detailSite property.
         * 
         * @return
         *     possible object is
         *     {@link DetailSite }
         *     
         */
        public DetailSite getDetailSite() {
            return detailSite;
        }

        /**
         * Sets the value of the detailSite property.
         * 
         * @param value
         *     allowed object is
         *     {@link DetailSite }
         *     
         */
        public void setDetailSite(DetailSite value) {
            this.detailSite = value;
        }

    }

}
