//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 03:33:32 PM ICT 
//


package com.ant.crawler.core.conf.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ant.crawler.core.conf.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ant.crawler.core.conf.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityConf }
     * 
     */
    public EntityConf createEntityConf() {
        return new EntityConf();
    }

    /**
     * Create an instance of {@link EntityConf.EntityFields }
     * 
     */
    public EntityConf.EntityFields createEntityConfEntityFields() {
        return new EntityConf.EntityFields();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link ListSite }
     * 
     */
    public ListSite createListSite() {
        return new ListSite();
    }

    /**
     * Create an instance of {@link DetailSite }
     * 
     */
    public DetailSite createDetailSite() {
        return new DetailSite();
    }

    /**
     * Create an instance of {@link Expand }
     * 
     */
    public Expand createExpand() {
        return new Expand();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link RssSite }
     * 
     */
    public RssSite createRssSite() {
        return new RssSite();
    }

    /**
     * Create an instance of {@link MappingField }
     * 
     */
    public MappingField createMappingField() {
        return new MappingField();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

}
